version: 2.1
jobs:
  build:
    docker:
      - image: 'circleci/openjdk:11-jdk'
    steps:
      - checkout
      - run:
          name: run-gradle
          command: ./gradlew sonarqube
workflows:
  version: 2
  main:
    jobs:
      - build:
          context: SonarCloud
