version: 2.1

jobs:
  build:
    docker:
      - image: 'circleci/openjdk:11-jdk'
    steps:
      - checkout
      - run:
          name: Analyze on SonarCloud
          command: gradle build sonarqube -Psonar.projectKey="siegfried-ehret-sonarsource_sq-com_example_java-gradle-travis" -Psonar.organization="siegfried-ehret-sonarsource" -Psonar.host.url="https://sieg.eu.ngrok.io"

workflows:
  main:
    jobs:
      - build:
          context: SonarCloud
